const assert=require('node:assert/strict');

module.exports=async function probarRegistro({page,navigate,response,screenshot,connection,today}) {
  await navigate('Pacientes');
  await page.getByRole('button',{name:'Nuevo Paciente',exact:true}).click();
  const modal=page.getByRole('dialog');
  await modal.getByRole('button',{name:/^Adulto/}).click();
  await modal.getByLabel('Nombres *',{exact:true}).fill('Elena');
  await modal.getByLabel('Apellidos *',{exact:true}).fill('Registro');
  await modal.getByLabel('Fecha de nacimiento *',{exact:true}).fill(today);
  await modal.getByRole('button',{name:'Continuar',exact:true}).click();
  await modal.getByText(/La fecha corresponde a un menor/).waitFor();
  await modal.getByLabel('Fecha de nacimiento *',{exact:true}).fill('1992-03-15');
  await modal.getByLabel('CI del paciente (opcional)').fill('12345678');
  await modal.getByRole('button',{name:'Continuar',exact:true}).click();
  await modal.getByLabel('Teléfono o referencia del paciente *',{exact:true}).fill('70000003');
  await modal.getByLabel('El paciente no dispone de correo; guardar como prerregistro').check();
  await page.setViewportSize({width:390,height:844});
  await screenshot('prerregistro-adulto-movil');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await modal.getByRole('button',{name:'Continuar',exact:true}).click();
  await modal.getByLabel('Confirmé los datos del paciente y el contacto para sus recordatorios.').check();
  const pendiente=await response(()=>modal.getByRole('button',{name:'Guardar prerregistro',exact:true}).click(),'/pacientes');
  assert.equal(pendiente.registro_pendiente,1);assert.equal(pendiente.email,null);
  const [[cola]]=await connection.query("SELECT COUNT(*) n FROM notificaciones_email WHERE paciente_id=? AND estado IN ('pendiente','error','enviado')",[pendiente.id]);
  assert.equal(cola.n,0);
  await page.setViewportSize({width:1440,height:1000});
  await modal.getByRole('button',{name:'Ver ficha del paciente',exact:true}).click();
  await page.getByText('Prerregistro pendiente de completar',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Editar Información',exact:true}).click();
  await modal.getByLabel('Nombres *',{exact:true}).waitFor();
  assert.equal(await modal.getByLabel('Nombres *',{exact:true}).inputValue(),'Elena');
  await modal.getByRole('button',{name:'Continuar',exact:true}).click();
  await modal.getByLabel('El paciente no dispone de correo; guardar como prerregistro').uncheck();
  await modal.getByLabel('Correo electrónico del paciente *',{exact:true}).fill('elena@example.invalid');
  await modal.getByRole('button',{name:'Continuar',exact:true}).click();
  await modal.getByLabel('Confirmé los datos del paciente y el contacto para sus recordatorios.').check();
  const completo=await response(()=>modal.getByRole('button',{name:'Guardar paciente',exact:true}).click(),'/pacientes/'+pendiente.id,'PUT');
  assert.equal(completo.registro_pendiente,0);assert.equal(completo.codigo_paciente,pendiente.codigo_paciente);
  await modal.getByRole('button',{name:'Ir a vacunación',exact:true}).click();
  await page.getByRole('heading',{name:'Registrar vacunación',exact:true}).waitFor();
  await page.getByRole('button',{name:'Cerrar registro de vacunación',exact:true}).click();

  await page.getByRole('button',{name:'Nuevo Paciente',exact:true}).click();
  await modal.getByRole('button',{name:/^Menor o recién nacido/}).click();
  await modal.getByLabel('Recién nacido sin nombre confirmado').check();
  await modal.getByLabel('Referencia familiar / apellidos (opcional)').fill('Registro');
  await modal.getByLabel('Fecha de nacimiento *',{exact:true}).fill(today);
  await modal.getByText('Edad calculada: 0 días',{exact:true}).waitFor();
  await modal.getByLabel('CI del paciente (opcional)').fill('12345678');
  await modal.getByRole('button',{name:'Continuar',exact:true}).click();
  await modal.getByLabel('Buscar tutor por nombre o CI').fill('Rosa Ensayo');
  await modal.getByRole('button',{name:/^Rosa Ensayo/}).click();
  assert.equal(await modal.getByLabel('Correo electrónico del paciente *',{exact:true}).count(),0);
  await modal.getByRole('button',{name:'Continuar',exact:true}).click();
  await modal.getByLabel('Confirmé los datos del paciente y el contacto para sus recordatorios.').check();
  const [[antes]]=await connection.query('SELECT COUNT(*) n FROM pacientes');
  const rechazo=page.waitForResponse(r=>new URL(r.url()).pathname.endsWith('/pacientes')&&r.request().method()==='POST');
  await modal.getByRole('button',{name:'Guardar prerregistro',exact:true}).click();
  assert.equal((await rechazo).status(),409);
  await modal.getByText(/Ya existe un paciente o tutor con ese documento/).waitFor();
  const [[despues]]=await connection.query('SELECT COUNT(*) n FROM pacientes');assert.equal(despues.n,antes.n);
  await modal.getByRole('button',{name:'Anterior',exact:true}).click();
  await modal.getByRole('button',{name:'Anterior',exact:true}).click();
  assert.equal(await modal.getByLabel('Referencia familiar / apellidos (opcional)').inputValue(),'Registro');
  await modal.getByLabel('CI del paciente (opcional)').fill('');
  await modal.getByRole('button',{name:'Continuar',exact:true}).click();
  await modal.getByRole('button',{name:'Continuar',exact:true}).click();
  await screenshot('revision-recien-nacido');
  await modal.getByLabel('Confirmé los datos del paciente y el contacto para sus recordatorios.').check();
  const recien=await response(()=>modal.getByRole('button',{name:'Guardar prerregistro',exact:true}).click(),'/pacientes');
  assert.equal(recien.identidad_provisional,1);assert.equal(recien.nombres,'Recién nacido');assert.equal(recien.carnet_identidad,null);
  assert.equal(recien.telefono_contacto,null);assert.equal(recien.email,null);assert.equal(recien.contacto_principal.nombre,'Rosa Ensayo');
  await modal.getByRole('button',{name:'Ver ficha del paciente',exact:true}).click();
  await page.getByRole('button',{name:'Editar Información',exact:true}).click();
  await modal.getByLabel('Recién nacido sin nombre confirmado').uncheck();
  await modal.getByLabel('Nombres *',{exact:true}).fill('Mateo');
  await modal.getByRole('button',{name:'Continuar',exact:true}).click();
  await modal.getByRole('button',{name:'Continuar',exact:true}).click();
  await modal.getByLabel('Confirmé los datos del paciente y el contacto para sus recordatorios.').check();
  const confirmado=await response(()=>modal.getByRole('button',{name:'Guardar paciente',exact:true}).click(),'/pacientes/'+recien.id,'PUT');
  assert.equal(confirmado.identidad_provisional,0);assert.equal(confirmado.registro_pendiente,0);assert.equal(confirmado.codigo_paciente,recien.codigo_paciente);
  await modal.getByRole('button',{name:'Cerrar',exact:true}).click();
};
